In [20]:
import numpy as np
arr= np.array([1,2,3,4])
print(arr)
type(arr)
print(arr.shape)

[1 2 3 4]
(4,)


In [36]:
import numpy as np
arr=np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
import numpy as np
arr=np.arange(24).reshape(4,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [42]:
import numpy as np
arr=np.arange(24).reshape(3,8)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [44]:
import numpy as np
arr=np.arange(24).reshape(8,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [46]:
import numpy as np
arr=np.arange(24).reshape(12,2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [48]:
import numpy as np
arr=np.arange(24).reshape(2,12)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [50]:
import numpy as np
arr=np.arange(24).reshape(24,1)
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [ ]:
import numpy as np
arr=np.arange(24).reshape(6,4)
arr

In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
import numpy as np
arr=np.ones((6,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
import numpy as np
arr=np.zeros((6,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
import numpy as np
arr=np.array([[1,0],[0,1]])
print(arr)

[[1 0]
 [0 1]]


In [17]:
import numpy as np
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
import numpy as np
arr=np.full((2,4),7)
print(arr)

[[7 7 7 7]
 [7 7 7 7]]


In [29]:
import numpy as np
arr=np.identity(6)
print(arr)
print(arr[:,:])
print(arr[2:5,0:3])

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


import numpy as np
arr=np.identity(6)
print(arr[0:2,0:5])
print(arr[0:2,0:5])
print(arr[2:4,2:4])
print(arr[-3:-1,-3:-1])
print(arr[-4:-1,-4:-1])

In [2]:
import numpy as np
arr=np.identity(6)
print(arr[0:2,0:5])
print(arr[2:4,2:4])
print(arr[-3:-1,-3:-1])
print(arr[-4:-1,-4:-1])


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [57]:
import numpy as np
a=np.array([2,2,2,2,2,2,2,2])
b=a.reshape(2,2,2)
print(b)
a.ndim


[[[2 2]
  [2 2]]

 [[2 2]
  [2 2]]]


1

In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.strides

(12, 4)

In [11]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.ndim

2

In [13]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.data

In [15]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.data

In [17]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.size

9

In [19]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.itemsize

4

In [35]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.base

In [29]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.nbytes

36

In [33]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [37]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.real

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.imag

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])